cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('checkout/', views.checkout, name='checkout'),
]

netshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('onlineshop.urls', namespace='onlineshop')),
    path('r', include('accounts.urls', namespace='accounts')),
    # path('reset/    ', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlineshop/urls.py
from django.urls import path
from . import views

app_name = 'onlineshop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('dash', views.dashboard, name='dashboard'),
    path('search', views.search_function, name='search'),

]

cart/models.py
from django.db import models
from django.contrib.auth.models import User

class UserAddress(models.Model):
    items = models.TextField()
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    address = models.TextField()
    contact = models.CharField(max_length=12)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    zip = models.IntegerField()
    price = models.IntegerField()
    cash_on_delivery = models.CharField(max_length=10, default=True)

    def __str__(self):
        return '%s %s %s' % (self.name, self.items, self.email)

cart/forms.py
from django import forms

choices = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=choices, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from onlineshop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .models import UserAddress

@require_POST       # to allow post request
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

@login_required(login_url='accounts:login')
def cart_detail(request):       # get current cart and display
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

def checkout(request):

    if request.method == 'POST':
        items = request.POST.get('products')
        name = request.POST.get('name')
        email = request.POST.get('email')
        address = request.POST.get('address')
        contact = request.POST.get('contact')
        city = request.POST.get('city')
        state = request.POST.get('state')
        zip = request.POST.get('zip')
        price = request.POST.get('price')
        cod = request.POST.get('payment')

        myaddress = UserAddress(items=items, name=name, email=email, address=address, contact=contact, city=city, state=state, zip=zip, price=price, cash_on_delivery=cod)
        myaddress.save()
        return render(request, 'cart/placed.html')

cart/templates/cart/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Checkout Page</title>
</head>
<body>
This is check page

{% for item in cart %}
{% with product=item.product %}
{{ product.name }}
{{ item.quantity }}
{% endwith %}
{% endfor %}
</body>
</html>

cart/templates/cart/detail.html
{% extends 'onlineshop/base.html' %}
{% load static %}

{% block title %}
Shopping Cart
{% endblock %}



<!--
<h2>Shopping Cart</h2>
<table class="cart">
  <thead>
  <tr>
    <th>Image</th>
    <th>Product</th>
    <th>Quantity</th>
    <th>Remove</th>
    <th>Unit Price</th>
    <th>Price</th>
  </tr>
  </thead>
  <tbody>
  <script>
  var products=[];
  {% for item in cart %}
  {% with product=item.product %}
  </script>
 <script>
    products['{{ product.id }}']='{{ product.name }}-{{item.quantity}}';
  var string=products.join(",");
  console.log(string);

 </script>
  <tr>
    <td>
      <a href="{{ product.get_absolute_url }}">
        <img class="card-img-top" style="width:250;height:230;" src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/no_image.png' %} {% endif %}">
      </a>
    </td>
    <td>{{ product.name }}</td>
    <td>
      {{ item.quantity }}
    </td>
    <td>
      <form action="{% url 'cart:cart_remove' product.id %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="Remove">
      </form>
    </td>
    <td class="num">
      Rs{{ item.price }}
    </td>
    <td class="num">
      Rs{{ item.total_price }}
    </td>
  </tr>
  {% endwith %}
  {% endfor %}
  <tr class="total">
    <td>Total</td>
    <td colspan="4"></td>
    <td class="num">Rs{{ cart.get_total_price }}</td>
  </tr>
  </tbody>
</table>
<p class="text-right">
  <a href="{% url 'onlineshop:product_list' %}" class="buttonlight">Continue Shopping</a>
</p>-->
<!--
<form method="POST" action="{% url 'cart:checkout' %}">
  {% csrf_token %}
<input type="text" id="prod" name="products" />
  Name:
  <input type="text" name="name" placeholder="Enter your name"/>
  <br>
  Email:
  <input type="email" name="email" placeholder="xyz@gmail.com"/>
  <br>
  Address:
  <input type="text" name="address" placeholder="No:30 herur kanchimane"/>
  <br>
  City:
  <input type="text" name="city" placeholder="Siddapur"/>
  <br>
  State:
  <input type="text" name="state" placeholder="Karnataka"/>
  <br>
  Zip Code:
  <input type="number" name="zip" placeholder="123456"/>
  <br>
  <br>
  <input type="submit" value="Place Order"/>
</form>
<script>
  document.getElementById("prod").value=string;
</script>
-->








{% block content %}

<div class="container_1 bg-light">
  <div class="row">
    <div class="col-12">
		<table class="table table-image">
		  <thead>
		    <tr>
		      <th scope="col">Serial No</th>
		      <th scope="col">Image</th>
		      <th scope="col">Name</th>
		      <th scope="col">Quantity</th>
				<th scope="col">Remove</th>
		      <th scope="col">Unit Price</th>
		      <th scope="col">Price</th>
		    </tr>
		  </thead>
		  <tbody>
		  <script>
  var products=[];
  {% for item in cart %}
  {% with product=item.product %}
  </script>
 <script>
    products['{{ product.id }}']='{{ product.name }}-{{item.quantity}}';
  var string=products.join(" , ");
  console.log(string);

 </script>
		    <tr>
		      <th scope="row">1</th>
		      <td class="w-25">
                  <a href="{{ product.get_absolute_url }}">
                    <img class="img-fluid" style="width:80% height:80%" src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/no_image.png' %} {% endif %}">
                  </a>
              </td>
		      <td style="padding-top:100px;">{{ product.name }}</td>
		      <td style="padding-top:100px;">{{ item.quantity }}</td>
		      <td style="padding-top:100px;"><form action="{% url 'cart:cart_remove' product.id %}" method="POST">
        {% csrf_token %}
        <input class="btn btn-outline-danger" type="submit" value="Remove">
      </form>
			  </td>
		      <td style="padding-top:100px;">{{ item.price }}</td>
				<td style="padding-top:100px;">{{ item.total_price }}</td>
		    </tr>
          {% endwith %}
		    {% endfor %}
		  </tbody>
		</table>
    </div>
  </div>
	<h4 style="float:right;">Total Price: Rs {{ cart.get_total_price }}</h4>
</div>
<script>
    var total_price = {{ cart.get_total_price }};
</script>
<style>
.container_1 {
  padding: 5rem 0rem;
}

h4 {
  margin: 5rem 0rem 1rem;
}

.table-image {
  td, th{
    vertical-align: middle;
  }

}

@media(min-width: 700px){
    .img-fluid{
        width:80%;
        height: 80%;
    }
}
</style>


<div class="container py-3">
    <h3>Address</h3>
<form class="row g-3" method="POST" action="{% url 'cart:checkout' %}">
  {% csrf_token %}
  <input type="hidden" id="prod" name="products"/>
    <input type="hidden" id="t_price" name="price"/>
  <div class="col-md-6">
    <label  class="form-label" style="color:blue;">Name</label>
    <input type="text" class="form-control" name="name">
  </div>
  <div class="col-md-6">
    <label class="form-label" style="color:blue;">Email</label>
    <input type="email" class="form-control" name="email">
  </div>
  <div class="col-12">
    <label  class="form-label" style="color:blue;">Address</label>
    <input type="text" class="form-control" name="address" placeholder="1234 Main St">
  </div>
  <div class="col-12">
    <label class="form-label" style="color:blue;">Contact Number</label>
    <input type="text" class="form-control" name="contact"/>
  </div>

  <div class="col-md-6">
    <label  class="form-label" style="color:blue;">City</label>
    <input type="text" class="form-control" name="city">
  </div>
  <div class="col-md-4">
    <label class="form-label" style="color:blue;">State</label>
    <input type="text" class="form-control" name="state">
  </div>
  <div class="col-md-2">
    <label class="form-label" style="color:blue;">Zip</label>
    <input type="number" class="form-control" name="zip">
  </div>
	<div class="form-check">
    <label class="form-label" style="color:blue;">Payment Method :</label><br>
  <input class="form-check-input" type="radio" name="payment" id="flexRadioDefault1" checked>
  <label class="form-check-label" for="flexRadioDefault1">
    Cash On Delivery
  </label>
</div>

  <div class="col-12">
    <button type="submit" class="btn btn-primary">Place Order</button>
  </div>
</form>
  <script>
  document.getElementById("prod").value=string;
  document.getElementById("t_price").value=total_price;
</script>
  </div>
{% endblock content %}

cart/templates/cart/placed.html
{% extends 'onlineshop/base.html' %}
{% block content %}
<div class="container py-5" style="margin-top:100px;">
<div class="jumbotron text-center">
  <h1 class="display-3">Thank You!</h1>
  <p class="lead">For Ordering Order placed successfully</p>
  <hr>
  <p>
    Having trouble? <a href="">Contact Us</a>
  </p>
  <p class="lead">
    <a class="btn btn-primary btn-sm" href="{% url 'onlineshop:product_list' %}" role="button">Continue Shopping</a>
  </p>
</div>
</div>
{% endblock content %}