accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.register, name='register'),
    path('login', views.login_req, name='login'),
    path('logout', views.logout_req, name='logout'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('checkout/', views.checkout, name='checkout'),
]

netshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('onlineshop.urls', namespace='onlineshop')),
    path('r', include('accounts.urls', namespace='accounts')),
    # path('reset/    ', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlineshop/urls.py
from django.urls import path
from . import views

app_name = 'onlineshop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('dash', views.dashboard, name='dashboard'),
    path('search', views.search_function, name='search'),

]

onlineshop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('onlineshop:product_list_by_category', args=[self.slug])
    
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    add_description = models.TextField(blank=True)
    add_image = models.CharField(max_length=1000, blank=True)
    add_image1 = models.CharField(max_length=1000, blank=True)
    add_image2 = models.CharField(max_length=1000, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('onlineshop:product_detail', args=[self.id, self.slug])

onlineshop/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.contrib.auth.models import User

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'onlineshop/product/list.html', {'category': category, 'categories': categories, 'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'onlineshop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})


def dashboard(request):
    _id = request.user
    user_id = _id.id
    users = get_object_or_404(User, id=user_id)
    return render(request, 'onlineshop/dash.html', {'users': users})


def search_function(request):
    if 'item' in request.GET:
        item_name = request.GET['item']
        products = Product.objects.all().filter(name__icontains=item_name)
    return render(request, 'onlineshop/product/list.html', {'products': products})

onlineshop/templates/onlineshop/base.html
{% load static %}
{% url 'cart:cart_detail' as cart_url %}
{% url 'onlineshop:product_list' as home %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MyShop{% endblock %}</title>
   <!-- <link href="{% static 'css/base.css' %}" rel="stylesheet"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src=
"https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js">
    </script>
 <script>
  $(document).ready(function () {
  // MDB Lightbox Init
  $(function () {
    $("#mdb-lightbox-ui").load("mdb-addons/mdb-lightbox-ui.html");
  });
});
</script>

</head>
<body>

<nav class="navbar navbar-expand-lg py-0 fixed-top navbar-dark bg-dark">
  <div class="container-fluid">
   <!--   <img src="{% static 'img/user_icon.png' %}"> -->
    <a class="navbar-brand" href="{% url 'onlineshop:dashboard' %}">{{ request.user.username | capfirst }}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == home %} active {% endif %}" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li {% if not category %} class="dropdown-item" {% endif %}>
            <a class="dropdown-item" href="{% url 'onlineshop:product_list' %}">All</a>
        </li>
            {% for c in categories %}
        <li {% if category.slug == c.slug %} class="dropdown-item" {% endif %}>
            <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
        {% endfor %}

          </ul>
        </li>
          <li class="nav-item">
          <a class="nav-link {% if request.path == cart_url %} active {% endif %}" aria-current="page" href="{% url 'cart:cart_detail' %}">Cart</a>
        </li>

      </ul>
      <form class="d-flex" action="{% url 'onlineshop:search' %}">
          {% csrf_token %}
        <input class="form-control me-2 mt-2" type="search" name="item" placeholder="Search" aria-label="Search">
        <input class="btn btn-outline-primary mt-2" type="submit">Search</input>
      </form>
      {% if user.is_authenticated %}
        <li class="nav-link">
          <a class="nav-link" style="color:red" aria-current="page" href="{% url 'accounts:logout' %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-link">
          <a class="nav-link text-white" aria-current="page" href="{% url 'accounts:login' %}">LogIn</a>
        </li>
      {% endif %}
    </div>
  </div>
</nav>

<div id="content"> <!-- div id = content -->
  {% block content %}
  {% endblock content %}
</div>

<!-- Footer -->
<footer class="text-center text-lg-start bg-dark text-white">

  <!-- Section: Social media -->
  <section
    class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
  >
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="https://facebook.com/dattu" target="_blank" class="me-4">
        <i class="fa fa-facebook fa-2x"></i>
      </a>
        <a href="#" class="me-4">
        <i style="color:green" class="fa fa-whatsapp fa-2x"></i>
      </a>
      <a href="https://twitter.com/dattu" class="me-4">
        <i style="color:blue" class="fa fa-twitter fa-2x"></i>
      </a>
      <a href="" class="me-4">
        <i style="color:red" class="fa fa-google fa-2x"></i>
      </a>
      <a href="https://instagram.com/dattu_h" class="me-4">
        <i style="color:purple" class="fa fa-instagram fa-2x"></i>
      </a>
      <a href="" class="me-4">
        <i style="color:powder" class="fa fa-linkedin fa-2x"></i>
      </a>
      <a href="" class="me-4">
        <i style="color:white" class="fa fa-github fa-2x"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>MyShop
          </h6>
          <p>
            Stay Home Stay Safe!
              Just Order Online.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="{% url 'onlineshop:product_list' %}" class="text-reset">Laptops</a>
          </p>
          <p>
            <a href="#" class="text-reset">SmartPhones</a>
          </p>
          <p>
            <a href="#" class="text-reset">Sensors</a>
          </p>
          <p>
            <a href="#" class="text-reset">TeleVisions</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Help
          </h6>
          <p>
            <a href="#" class="text-reset">Returns & Exchange</a>
          </p>
          <p>
            <a href="#" class="text-reset">Terms & Conditions</a>
          </p>
          <p>
            <a href="#" class="text-reset">Privacy Policy</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Have a Questions ?
          </h6>
          <p><i class="fa fa-home me-3"></i>Herur Siddapur Uttara Kannada Karnataka 581450</p>
          <p>
            <i class="fa fa-envelope me-3"></i>
            dattukanchi@gmail.com
          </p>
          <p><i class="fa fa-phone me-3"></i> + 91 9482759323</p>
          <p><i class="fa fa-phone me-3"></i> + 91 8660567969</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="#">Dattu Hegde</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
</body>
</html>

onlineshop/templates/onlineshop/dash.html
{% extends 'onlineshop/base.html' %}
{% block content %}

<div class="container py-5 mt-5 bg-light">
<div class="row gutters">
<div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
<div class="card h-100">
	<div class="card-body">
		<div class="account-settings">
			<div class="user-profile">
				<div class="user-avatar">
					<img src="https://bootdey.com/img/Content/avatar/avatar7.png" style="width:200px" alt="Maxwell Admin">
				</div>
				<h5 class="user-name">{{ users.username }}</h5>
				<h6 class="user-email">{{ users.email }}</h6>
			</div>

		</div>
	</div>
</div>
</div>
<div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
<div class="card h-100">
	<div class="card-body">
		<div class="row gutters">
			<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
				<h6 class="mb-2 text-primary">Personal Details</h6>
			</div>
			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
				<div class="form-group">
					<label for="fullName">Name</label>
					<input type="text" class="form-control" id="fullName" value="{{ request.user.username }}">
				</div>
			</div>
			<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
				<div class="form-group">
					<label for="eMail">Email</label>
					<input type="email" class="form-control" id="eMail" value="{{ request.user.email }}">
				</div>
			</div>

		</div>

		<div class="row gutters">
			<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
			</div>
		</div>
	</div>
</div>
</div>
</div>
</div>
{% endblock content %}