cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('checkout/', views.checkout, name='checkout'),
]

netshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('onlineshop.urls', namespace='onlineshop')),
    path('r', include('accounts.urls', namespace='accounts')),
    # path('reset/    ', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlineshop/urls.py
from django.urls import path
from . import views

app_name = 'onlineshop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('dash', views.dashboard, name='dashboard'),
    path('search', views.search_function, name='search'),

]

onlineshop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('onlineshop:product_list_by_category', args=[self.slug])
    
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    add_description = models.TextField(blank=True)
    add_image = models.CharField(max_length=1000, blank=True)
    add_image1 = models.CharField(max_length=1000, blank=True)
    add_image2 = models.CharField(max_length=1000, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('onlineshop:product_detail', args=[self.id, self.slug])

onlineshop/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.contrib.auth.models import User

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'onlineshop/product/list.html', {'category': category, 'categories': categories, 'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'onlineshop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})


def dashboard(request):
    _id = request.user
    user_id = _id.id
    users = get_object_or_404(User, id=user_id)
    return render(request, 'onlineshop/dash.html', {'users': users})


def search_function(request):
    if 'item' in request.GET:
        item_name = request.GET['item']
        products = Product.objects.all().filter(name__icontains=item_name)
    return render(request, 'onlineshop/product/list.html', {'products': products})

onlineshop/templates/onlineshop/product/detail.html
{% extends 'onlineshop/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
{{ product.name }}
{% endblock %}

{% block content %}
<main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <a href="{{ product.image.url }}">
                  <img class=" card-img-top" style="width:500px; height:350px;" src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/no_image.png' %} {% endif %}">
              </a>
        </div>
        <!--Grid column-->
        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <!--Content-->
          <div class="p-5">
            <p><h5>{{ product.name }}</h5></p>
            <p class="lead">
              <span class="mr-1">
                <span>Rs</span>
              </span>
              <span>{{ product.price }}</span>
            </p>
            <h5>Description </h5>
            <p>{{ product.description }}</p>
            <form class="d-flex justify-content-left" action="{% url 'cart:cart_add' product.id %}" method="POST">
              <!-- Default input -->
              {{ cart_product_form | crispy}}
              {% csrf_token %}
              <input type="submit" class="form-control btn btn-primary  m-4" value="Add to Cart" style="width:150px;">
            </form>
          </div>
          <!--Content-->
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
      <hr>
      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">
        <!--Grid column-->
        <div class="col-md-6 text-center">
          <h4 class="my-4 h4">Additional information</h4>
          <p> {{ product.add_description }}</p>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
      <!--Grid row-->
      <div class="row wow fadeIn">
        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">
          <a href="{{ product.add_image }}"><img src="{{ product.add_image }}" class="img-fluid" alt=""> </a>
        </div>
        <!--Grid column-->
        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">
          <a href="{{ product.add_image1 }}"> <img src="{{ product.add_image1 }}" class="img-fluid" alt=""></a>
        </div>
        <!--Grid column-->
        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">
          <a href="{{ product.add_image2 }}"> <img src="{{ product.add_image2 }}" class="img-fluid" alt=""></a>
        </div>
      </div>
    </div>
  </main>
  <!--Main layout-->
<!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">
    <!--Call to action-->
    <div class="pt-4">
    </div>
    <!--/.Call to action-->
    <hr class="my-4">
  </footer>
  <!--/.Footer-->
{% endblock content %}

onlineshop/templates/onlineshop/product/list.html
{% extends 'onlineshop/base.html' %}
{% load static %}
{% block title %}
{% if category %}
{{ category.name }}
{% else %}
Products
{% endif %}
{% endblock %}
{% block content %}


<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>List-products</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">
    <!-- Bootstrap core CSS -->
    <link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
</head>
<body>
<main>
    <!-- SlideShow Cover Images -->
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                    aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                    aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'img/n_c.jpg' %}" class="d-block" style="width:100%; height:665px;" alt="laptop on">
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/new_cover_1.jpg' %}" class="d-block" style="width:100%; height:665px;"
                     alt="new cover image">
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/cover4.jpg' %}" class="d-block" style="width:100%; height:665px;"
                     alt="computer on table">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

    <div class="container py-3">
        <div class="row mt-3 text-center" >
            <div class="col">
                <img src="{% static 'img/truck.gif' %}" width="100px" height="100px">
                <p>Fast Delivery</p>
                <p class=" text-muted">Speed Delivery</p>
            </div>
            <div class="col">
                <img src="{% static 'img/qua.gif' %}" width="100px" height="100px">
                <p>Quality Products</p>
                <p class=" text-muted">Good Products</p>
            </div>
            <div class="col">
                <img src="{% static 'img/package.gif' %}" width="100px" height="100px">
                <p>Well Packed</p>
                <p class=" text-muted">Products Sanitized</p>
            </div>
            <div class="col">
                <img src="{% static 'img/trust.gif' %}" width="100px" height="100px">
                <p>Customer Support</p>
                <p class=" text-muted">24x7 Support</p>
            </div>

        </div>
    </div>

    <div class="album py-3 bg-light">
        <div class="py-5 bg-white">
            <div class="container">
                <h3 class="text-center">Our Products</h3>
            </div>
        </div>
        <div class="container py-3">
            <div class="row">
                {% for product in products %}
                <div class="card-group col-md-3 my-3">

                    <div class="card shadow-sm" style="width:15rem;">
                        <a href="{{ product.get_absolute_url }}">
                            <img class="bd-placeholder-img card-img-top" width="100%"
                                 src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/no_image.png' %} {% endif %}">
                        </a>
                        <div class="card-body">
                            <h5 class="card-title">{{ category.name }}</h5>
                            <a class="card-link" style="text-decoration:none;" href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                            Rs {{ product.price }}<br>
                            <div class="d-flex justify-content-between align-items-center"><br>
                                <div class="card-footer" style="width:100%">
                                <p class="text-muted">{{ product.created }}</p>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>

                {% endfor %}
            </div>
        </div>
    </div>
</main>


<script src="/docs/5.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>
{% endblock content %}