accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.register, name='register'),
    path('login', views.login_req, name='login'),
    path('logout', views.logout_req, name='logout'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('checkout/', views.checkout, name='checkout'),
]

netshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('onlineshop.urls', namespace='onlineshop')),
    path('r', include('accounts.urls', namespace='accounts')),
    # path('reset/    ', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'is_staff')
        widgets = {'is_staff': forms.HiddenInput()}

    def save(self, commit=True):
        user = super(NewForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        self.fields['is_staff'].widget = forms.HiddenInput()
        if commit:
            user.save()
        return user

accounts/views.py
from django.shortcuts import render, redirect
from .forms import NewForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm

def register(request):
    if request.method == 'POST':
        form = NewForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('onlineshop:product_list')
        return render(request, 'accounts/register.html', {'register_form': form})
    form = NewForm()
    return render(request, 'accounts/register.html', {'register_form': form})

def login_req(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                # messages.info(request, f"You are now logged in as {username}.")
                return redirect('onlineshop:product_list')
            else:
                return render(request, 'accounts/login.html', {'login_form': form})
        else:
            return render(request, 'accounts/login.html', {'login_form': form})
    form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'login_form': form})

def logout_req(request):
    logout(request)
    return redirect('onlineshop:product_list')

accounts/templates/accounts/login.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% load crispy_forms_tags %}
<div class="container py-3" style="width:450px;">
  <h1 style="text-align:center;">Login</h1>

  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="{% url 'accounts:register' %}">Create an account</a>.</p>
</div>

accounts/templates/accounts/register.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% load crispy_forms_tags %}
<div class="container py-3" style="width:450px;">
    <h1 style="text-align:center;">Register</h1>
    {% if error %}
    {{ error }}
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {{ register_form | crispy }}
        <button class="btn btn-primary" type="submit">Register</button>
    </form>
    <p class="text-center">If you already have an account, <a href="{% url 'accounts:login' %}">login</a> instead.</p>
</div>